### ISSUE TITLE
Ý tưởng tốt đó em.

### ISSUE THREAD

**Issue by quocthinhvo** [minhquan-onG1team/kodeman#1]
Anh có vài góp ý nhỏ
- Nếu em phát triển thêm tính năng kiểu GUI Install thì ngon
- anh sẽ fork về trang GitHub của nhóm Kode Studio nhé

**Comment by kun-kode** [comment]
Ok anh.
Nhưng GUI Install thì em nghĩ bên Windows sẽ có chứ bên Linux chắc lấy file shell để execute thôi :VVV
________________________________
Từ: Quốc Thịnh Võ <notifications@github.com>
Đã gửi: 09 Tháng Tám 2020 10:08 CH
Đến: minhquan-onG1team/kodeman <kodeman@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Chủ đề: [minhquan-onG1team/kodeman] Ý tưởng tốt đó em. (#1)


Anh có vài góp ý nhỏ

  *   Nếu em phát triển thêm tính năng kiểu GUI Install thì ngon
  *   anh sẽ fork về trang GitHub của nhóm Kode Studio nhé

**Comment by quocthinhvo** [comment]
Công nhận tiếng anh em cứng :V
